## Data Lakehouse stack with Spark + Iceberg + REST Catalog over JDBC

services:
  ray-jupyter:
    container_name: ray-head
    env_file:
      - .env
    build:
      context: ./ray-head
    shm_size: 3g
    networks:
      iceberg_net:
    #volumes:
    #  - ./ray-head:/app
    ports:
      - 8265:8265
      - 6379:6379
      - 8888:8888
  rest:
    image: tabulario/iceberg-rest
    env_file: catalog.env
    container_name: iceberg-rest
    networks:
      iceberg_net:
    ports:
      - 8181:8181
    volumes:
      - ${CATALOG_DB_DIR}:/home/iceberg

networks:
  iceberg_net:
